#!/bin/bash

#CMD="$@:-/bin/bash"
PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc > /dev/null 2>&1
usermod -o -u "$PUID" abc > /dev/null 2>&1

chown -R ${PUID}:${PGID} /app
export HOME="/app"

eval s6-setuidgid abc "$@"
