AWSTemplateFormatVersion: 2010-09-09
Description: Terraform S3 Backend and DynamoDB Lock Table
Parameters:
  StateBucketName:
    Description: Name to give the State Backend bucket
    Type: String
  StateTableName:
    Description: Name to give the State Backend table
    Type: String
Resources:
  TerraformStateBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref StateBucketName
      AccessControl: "Private"
      VersioningConfiguration:
        Status: Enabled
  TerraformStateTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref StateTableName

Outputs:
  StackName:
    Value: !Ref AWS::StackName
  StateBucketName:
    Description: Name of the State Backend bucket
    Value: !Ref StateBucketName
  StateTableName:
    Description: Name of the State Backend table
    Value: !Ref StateTableName
